spring:
  application:
    name: graphql-example

  graphql:
    graphiql:
      path: /graphiql
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: CCS-L1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
